# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r_check_args: --as-cran
sudo: false
cache: packages
warnings_are_errors: false


matrix:
  include:
    - os: linux
      r: release
      r_packages:
        - pkgdown
        - devtools
      after_success:
        - R CMD INSTALL .
        - Rscript -e "devtools::document(roclets = c('rd', 'collate', 'namespace'))"
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_PAT
          keep-history: true
          local-dir: docs
          on:
            branch: master
