# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r_check_args: --as-cran

sudo: false

cache: packages

warnings_are_errors: false

os:
  - osx
  - linux

r:
  - 3.5
  - 3.6

after_success:
  - Rscript -e 'covr::codecov()'
