# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warning_as_error: false

os:
  - osx
  - linux

r:
  - 3.5
  - 3.6

after_success:
  - Rscript -e 'covr::codecov()'
